// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXM6wY-AC36BjhLFWBj6a7QMK4xD989tQ',
    appId: '1:74983273570:web:9131647beab31105c40d3b',
    messagingSenderId: '74983273570',
    projectId: 'umay-330e8',
    authDomain: 'umay-330e8.firebaseapp.com',
    storageBucket: 'umay-330e8.firebasestorage.app',
    measurementId: 'G-MMQ6SH2RP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHpg0f9MCvNlg5_h2ylBNZNLqpizRhC8s',
    appId: '1:74983273570:android:7c6e6a4693d49da1c40d3b',
    messagingSenderId: '74983273570',
    projectId: 'umay-330e8',
    storageBucket: 'umay-330e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3vJaGsSBtr2kgypP4R0g4TH2mtX95TEs',
    appId: '1:74983273570:ios:4bf6bc14386f2b81c40d3b',
    messagingSenderId: '74983273570',
    projectId: 'umay-330e8',
    storageBucket: 'umay-330e8.firebasestorage.app',
    iosBundleId: 'com.example.gebelikAapp',
  );
}
